spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        time_zone_storage: NORMALIZE_UTC
  web:
    resources:
      add-mappings: false
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-expiration-milliseconds: 3600000
    refresh-token-expiration-milliseconds: 604800000
  data:
    redis:
      host: redis-server
      port: 6379
